#pragma once

typedef enum event_type
{
    EVT_UNDEFINED = 0,
    
    EVT_WINDOW_CLOSE,
	EVT_WINDOW_RESIZE,
	EVT_WINDOW_MOVED,
	EVT_WINDOW_MAXIMIZED,
	EVT_WINDOW_FOCUS_CHANGED,
	EVT_WINDOW_FRAMEBUFFER_RESIZE,
	EVT_WINDOW_CONTENT_SCALE,

    EVT_KEY_PRESSED,
	EVT_KEY_RELEASED,
	EVT_KEY_REPEAT,

	EVT_MOUSE_PRESSED,
	EVT_MOUSE_RELEASED,
	EVT_MOUSE_SCROLL,
	EVT_MOUSE_MOVE,

    EVENT_TYPE_AMOUNT
} event_type;